### ISSUE TITLE
Section 4.4.3. on Remotely-keyed encryption

### ISSUE THREAD

**Issue by jedisct1** [AndAlBo/draft-irtf-cfrg-aead-properties#12]
Remotely-keyed encryption is mainly a *protoocol* between a high-bandwidth device that hasn't access to the key (but can access the plaintext and ciphertext), and another device that has the key, with minimal communication between both.

I'm not sure that this qualifies as an AEAD property.

**Comment by AndAlBo** [comment]
Yes, I agree with that. Additional functionality properties do not apply to conventional AEADs; they all require a different interface, although they can all be redefined as conventional AEADs. Incremental AEADs are not strictly AEADs either. Such AEADs also require a redefinition of basic confidentiality and integrity.

Since additional functionality properties are not truly properties, I will relocate them from Section 4 to a separate section "AEAD algorithms with additional functionality," and briefly describe what they do in addition to the usual AEAD functionality.

**Comment by jedisct1** [comment]
Should these even be part of this document?

They are AEAD-based constructions (and can also depend on other primitive types such as hash functions), with specific interfaces, different definitions of confidentiality and integrity, and can hardly be listed extensively.

Xoodyak-like modes also include AEAD capabilities, authenticating the entire transcript. I guess session support should also be part of that section. But my fear is that such section would eventually become way too large and complicated.

Maybe it would be better to remain focused on properties of AEADs primitives with a standard interface, and perhaps augment this document later with another document about other AEAD classes.

**Comment by AndAlBo** [comment]
Yes, that makes sense; I agree the document shouldn't be focusing on enumerating AEADs with additional functionality.
I will leave incremental and robust AEADs as examples of such classes in the appendix to provide some intuition on the difference between security properties and additional functionality (and also because I was told a document about AEAD classes is highly unlikely, so it would be nice to mention them at least briefly).

**Comment by AndAlBo** [comment]
Done with commit 2788a89.
